services:
  cucumber:
    image: maven:3.8.6-jdk-11
    working_dir: /usr/src/workdir
    init: true
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ./cucumber/hellocucumber:/usr/src/workdir
      - ./cucumber/maven-repository:/root/.m2
  chrome:
    image: selenium/standalone-chrome:98.0-20250303
    ports:
      - 4444:4444
      - 7900:7900
  flask:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    volumes:
      - ./flask/app:/app
    ports:
      - "8001:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONPYCACHEPREFIX=/tmp/pycache
    command: flask run --host=0.0.0.0 --port=80
