version: '3.9'
services:
  tester:
    build: .
    volumes:
      - ./hellocucumber:/usr/src/mymaven
  chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
      - 4444:4444
      - 5900:5900
